version: "3.7"

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: peso_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5445:5432"
  
volumes:
  db-data: